export const ACTOR_REQUEST = "ACTOR_REQUEST";
export const ACTOR_SUCCESS = "ACTOR_SUCCESS";
export const ACTOR_FAILURE = "ACTOR_FAILURE";
export const ADD_ACTOR_REQUEST = "ADD_ACTOR_REQUEST";
export const ADD_ACTOR_SUCCESS = "ADD_ACTOR_SUCCESS";
export const ADD_ACTOR_FAILURE = "ADD_ACTOR_FAILURE";
export const DELETE_ACTOR_REQUEST = "DELETE_ACTOR_REQUEST";
export const DELETE_ACTOR_SUCCESS = "DELETE_ACTOR_SUCCESS";
export const DELETE_ACTOR_FAILURE = "DELETE_ACTOR_FAILURE";

const types = {
    ACTOR_REQUEST,
    ACTOR_SUCCESS,
    ACTOR_FAILURE,
    ADD_ACTOR_REQUEST,
    ADD_ACTOR_SUCCESS,
    ADD_ACTOR_FAILURE,
    DELETE_ACTOR_REQUEST,
    DELETE_ACTOR_SUCCESS,
    DELETE_ACTOR_FAILURE,
};

export default types;
