export const MOVIE_REQUEST = "MOVIE_REQUEST";
export const MOVIE_SUCCESS = "MOVIE_SUCCESS";
export const MOVIE_FAILURE = "MOVIE_FAILURE";
export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE";
export const EDIT_MOVIE_REQUEST = "EDIT_MOVIE_REQUEST";
export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_FAILURE = "EDIT_MOVIE_FAILURE";
export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE";
export const NONE_DIRECTOR_REQUEST = "NONE_DIRECTOR_REQUEST";
export const NONE_DIRECTOR_SUCCESS = "NONE_DIRECTOR_SUCCESS";
export const NONE_DIRECTOR_FAILURE = "NONE_DIRECTOR_FAILURE";

const types = {
    MOVIE_REQUEST,
    MOVIE_SUCCESS,
    MOVIE_FAILURE,
    ADD_MOVIE_REQUEST,
    ADD_MOVIE_SUCCESS,
    ADD_MOVIE_FAILURE,
    EDIT_MOVIE_REQUEST,
    EDIT_MOVIE_SUCCESS,
    EDIT_MOVIE_FAILURE,
    DELETE_MOVIE_REQUEST,
    DELETE_MOVIE_SUCCESS,
    DELETE_MOVIE_FAILURE,
    NONE_DIRECTOR_REQUEST,
    NONE_DIRECTOR_SUCCESS,
    NONE_DIRECTOR_FAILURE,
};

export default types;
