export const PERSON_REQUEST = "PERSON_REQUEST";
export const PERSON_SUCCESS = "PERSON_SUCCESS";
export const PERSON_FAILURE = "PERSON_FAILURE";
export const ADD_PERSON_REQUEST = "ADD_PERSON_REQUEST";
export const ADD_PERSON_SUCCESS = "ADD_PERSON_SUCCESS";
export const ADD_PERSON_FAILURE = "ADD_PERSON_FAILURE";
export const EDIT_PERSON_REQUEST = "EDIT_PERSON_REQUEST";
export const EDIT_PERSON_SUCCESS = "EDIT_PERSON_SUCCESS";
export const EDIT_PERSON_FAILURE = "EDIT_PERSON_FAILURE";
export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_FAILURE = "DELETE_PERSON_FAILURE";

const types = {
    PERSON_REQUEST,
    PERSON_SUCCESS,
    PERSON_FAILURE,
    ADD_PERSON_REQUEST,
    ADD_PERSON_SUCCESS,
    ADD_PERSON_FAILURE,
    EDIT_PERSON_REQUEST,
    EDIT_PERSON_SUCCESS,
    EDIT_PERSON_FAILURE,
    DELETE_PERSON_REQUEST,
    DELETE_PERSON_SUCCESS,
    DELETE_PERSON_FAILURE,
};

export default types;
